const fileInput=document.getElementById("fileInput"),chooseBtn=document.getElementById("chooseBtn"),dropZone=document.getElementById("dropZone"),statusCard=document.getElementById("statusCard"),resultCard=document.getElementById("resultCard"),fileName=document.getElementById("fileName"),statusText=document.getElementById("statusText"),progressBar=document.getElementById("progressBar"),resultTitle=document.getElementById("resultTitle"),resultDetails=document.getElementById("resultDetails"),downloadBtn=document.getElementById("downloadBtn"),visualPdf=document.getElementById("visualPdf"),recompressImages=document.getElementById("recompressImages");
let resultBlob=null,resultFileName="";
if(window.pdfjsLib) pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
chooseBtn.addEventListener("click",()=>fileInput.click());fileInput.addEventListener("change",()=>{if(fileInput.files[0])processFile(fileInput.files[0])});
["dragenter","dragover"].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.add("dragover")}));["dragleave","drop"].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.remove("dragover")}));dropZone.addEventListener("drop",e=>{const f=e.dataTransfer.files[0];if(f)processFile(f)});
downloadBtn.addEventListener("click",()=>{if(!resultBlob)return;const u=URL.createObjectURL(resultBlob),a=document.createElement("a");a.href=u;a.download=resultFileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)});
function setProgress(v,t){progressBar.style.width=`${Math.max(0,Math.min(100,v))}%`;statusText.textContent=t}function formatBytes(b){if(b<1024)return`${b} B`;const u=["KB","MB","GB"],v0=b/1024;let v=v0,u0=u[0],i=0;while(i+1<u.length&&v>=1024){v/=1024;i++;u0=u[i]}return`${v.toFixed(v>=100?0:1)} ${u0}`}function savedPct(a,b){return Math.max(0,Math.round((a-b)/a*100))}
async function processFile(file){const ext=file.name.split(".").pop().toLowerCase();if(!["pdf","docx","pages"].includes(ext)){showResult("Unsupported file","Choose PDF, DOCX or Pages.",false);return}if(file.size>100*1024*1024){showResult("File is too large","The current browser version accepts files up to 100 MB.",false);return}statusCard.classList.remove("hidden");resultCard.classList.add("hidden");fileName.textContent=file.name;setProgress(4,"Analyzing file…");try{const r=ext==="pdf"?await optimizePdf(file):await optimizeOfficePackage(file);setProgress(100,"Finished");if(!r||r.blob.size>=file.size){resultBlob=file;resultFileName=file.name;showResult("Already well optimized",`${formatBytes(file.size)} — no processed version was smaller without risking quality or content.`,true);return}resultBlob=r.blob;resultFileName=file.name.replace(/\.(pdf|docx|pages)$/i,"")+"-cominify."+ext;const s=file.size-r.blob.size,p=savedPct(file.size,r.blob.size);showResult("File successfully reduced",`${formatBytes(file.size)} → ${formatBytes(r.blob.size)} · saved ${formatBytes(s)} (${p}%) · ${r.method||"optimization"}`,true)}catch(e){console.error(e);setProgress(0,"Error");showResult("Could not process this file","The original file was not changed. Try another document or a smaller file.",false)}}
async function optimizePdf(file){const bytes=await file.arrayBuffer(),c=[];setProgress(16,"Optimizing PDF structure…");try{c.push({blob:await safePdfOptimization(bytes),method:"safe PDF optimization"})}catch(e){console.warn(e)}if(visualPdf.checked&&window.pdfjsLib&&window.jspdf){try{setProgress(30,"Testing maximum visual compression…");c.push({blob:await rasterPdfOptimization(bytes),method:"maximum visual PDF optimization"})}catch(e){console.warn(e)}}if(!c.length)throw Error("No PDF candidate");c.sort((a,b)=>a.blob.size-b.blob.size);return c[0]}
async function safePdfOptimization(bytes){const pdf=await PDFLib.PDFDocument.load(bytes,{ignoreEncryption:true,updateMetadata:false});pdf.setTitle("");pdf.setAuthor("");pdf.setSubject("");pdf.setKeywords([]);pdf.setCreator("");pdf.setProducer("");const out=await pdf.save({useObjectStreams:true,addDefaultPage:false,updateFieldAppearances:false,objectsPerTick:50});return new Blob([out],{type:"application/pdf"})}
async function rasterPdfOptimization(bytes){const pdf=await pdfjsLib.getDocument({data:bytes,useWorkerFetch:true,isEvalSupported:true}).promise,{jsPDF}=window.jspdf;let out=null;const dpi=150,q=.78;for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),base=page.getViewport({scale:1});let vp=page.getViewport({scale:dpi/72}),max=2600,side=Math.max(vp.width,vp.height);if(side>max)vp=page.getViewport({scale:dpi/72*max/side});const c=document.createElement("canvas");c.width=Math.max(1,Math.floor(vp.width));c.height=Math.max(1,Math.floor(vp.height));const ctx=c.getContext("2d",{alpha:false});ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);await page.render({canvasContext:ctx,viewport:vp}).promise;const jpg=await canvasToDataURL(c,q),pw=base.width,ph=base.height;if(!out)out=new jsPDF({orientation:pw>ph?"landscape":"portrait",unit:"pt",format:[pw,ph],compress:true});else out.addPage([pw,ph],pw>ph?"landscape":"portrait");out.addImage(jpg,"JPEG",0,0,pw,ph,undefined,"FAST");setProgress(30+Math.round(n/pdf.numPages*58),`Compressing PDF page ${n}/${pdf.numPages}…`);c.width=1;c.height=1}return new Blob([out.output("arraybuffer")],{type:"application/pdf"})}
function canvasToDataURL(c,q){return new Promise((res,rej)=>c.toBlob(b=>{if(!b)return rej(Error("JPEG encoding failed"));const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(b)},"image/jpeg",q))}
async function optimizeOfficePackage(file){const input=await JSZip.loadAsync(await file.arrayBuffer()),output=new JSZip(),names=Object.keys(input.files).filter(n=>!input.files[n].dir&&!n.startsWith("__MACOSX/")&&!n.endsWith(".DS_Store"));let done=0;for(const name of names){const e=input.files[name];if(recompressImages.checked&&/^word\/media\//i.test(name)&&/\.(jpe?g|png)$/i.test(name)){const bytes=await e.async("uint8array");try{const opt=await optimizeEmbeddedImage(new Blob([bytes]),name);if(opt&&opt.blob.size<bytes.byteLength*.97){if(opt.name!==name)await addEntryWithRenamedReference(output,input,names,name,opt.name,opt.blob);else addFile(output,name,opt.blob)}else addFile(output,name,bytes)}catch{addFile(output,name,bytes)}}else addFile(output,name,await e.async("uint8array"));done++;setProgress(15+Math.round(done/names.length*72),"Rebuilding document…")}const blob=await output.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:9},mimeType:file.name.toLowerCase().endsWith(".docx")?"application/vnd.openxmlformats-officedocument.wordprocessingml.document":"application/octet-stream"});return{blob,method:"package + embedded image optimization"}}
function addFile(z,n,d){z.file(n,d,{compression:"DEFLATE",compressionOptions:{level:9},date:new Date(0)})}
async function addEntryWithRenamedReference(output,input,names,oldName,newName,optBlob){const oldTarget=oldName.replace(/^word\//i,""),newTarget=newName.replace(/^word\//i,"");for(const name of names){if(name===oldName){addFile(output,newName,optBlob);continue}let d=await input.files[name].async("uint8array");if(/\.rels$/i.test(name)||/(\.xml|\.vml)$/i.test(name)){const t=new TextDecoder().decode(d);if(t.includes(oldTarget))d=new TextEncoder().encode(t.split(oldTarget).join(newTarget))}addFile(output,name,d)}}
async function optimizeEmbeddedImage(blob,name){const type=blob.type||guessMime(name);if(!/^image\/(jpeg|png)$/i.test(type))return null;const img=await loadImage(blob),ow=img.naturalWidth,oh=img.naturalHeight,max=2200;let w=ow,h=oh;if(Math.max(w,h)>max){const s=max/Math.max(w,h);w=Math.max(1,Math.round(w*s));h=Math.max(1,Math.round(h*s))}const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{alpha:type==="image/png"});if(type==="image/jpeg"){ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h)}ctx.drawImage(img,0,0,w,h);if(type==="image/jpeg")return{blob:await canvasBlob(c,"image/jpeg",.78),name};const png=await canvasBlob(c,"image/png");if(png.size<blob.size*.97)return{blob:png,name};const jpg=await canvasBlob(c,"image/jpeg",.80);if(jpg.size<blob.size*.70)return{blob:jpg,name:name.replace(/\.png$/i,".jpg")};return{blob,name}}
function guessMime(n){return/\.jpe?g$/i.test(n)?"image/jpeg":/\.png$/i.test(n)?"image/png":"application/octet-stream"}function loadImage(blob){return new Promise((res,rej)=>{const u=URL.createObjectURL(blob),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);res(i)};i.onerror=e=>{URL.revokeObjectURL(u);rej(e)};i.src=u})}function canvasBlob(c,t,q){return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(Error("Image encoding failed")),t,q))}
function showResult(title,details,canDownload){resultCard.classList.remove("hidden");resultTitle.textContent=title;resultDetails.textContent=details;downloadBtn.disabled=!canDownload;downloadBtn.style.opacity=canDownload?"1":".45";downloadBtn.style.pointerEvents=canDownload?"auto":"none"}
